# Generated by Django 5.0.6 on 2024-06-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_guide',
            name='place_loc',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reg_guide',
            name='aadhar_num',
            field=models.CharField(max_length=10),
        ),
    ]
