# Generated by Django 5.0.6 on 2024-06-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reg_guide_place_loc_alter_reg_guide_aadhar_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_guide',
            name='price',
            field=models.IntegerField(default=2444, max_length=4),
            preserve_default=False,
        ),
    ]
