# Generated by Django 5.0.6 on 2024-06-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reg_guide_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_guide',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
